question_data = [
        {"category": "Entertainment: Musicals & Theatres", "type": "boolean", "difficulty": "easy",
         "question": "In the play Oedipus Rex, Oedipus kills his father due to jealousy in loving his mother.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
         "question": "Eurobeat is primarily an Italian genre of music.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                           "question": "There is a city called Rome in every continent on Earth.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "easy",
         "question": "Deadpool&#039;s identity is Slade Wilson.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "The Lego Group was founded in 1932.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In Pok&eacute;mon, Arbok evolves into Seviper.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                          "question": "Hungary is the only country in the world beginning with H.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
         "question": "&quot;Green Eggs and Ham&quot; consists of only 50 different words.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                           "question": "John Williams composed the music for &quot;Star Wars&quot;.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]}]
